### ISSUE TITLE
Picture Pin Connection

### ISSUE THREAD

**Issue by Regunova** [PepeTheFroggie/Soyosource-GridTie-inverter-24V-LCD-replacement#1]
Not sure, but I think the pins tx rx on the ESP8266 Board must be used . Not D8 D7.
For 5V Soyo to 3,3V ESP I would use a Voltage Divider.  1k Soyo Tx to ESP Rx and 1,5k to GND.

**Comment by PepeTheFroggie** [comment]
If you use the normal rx/tx pins you run into problems with the serial-usb converter.
That is the reason to use swap(); in setup which changes rx/tx pins.

This code:
-----------
Serial.println("Switching to alt. Port now");
delay(500);
Serial.swap(); //Tx = GPIO15, Rx = GPIO13
